---
- name: Gebruik een template om de motd te vullen met informatie uit facts
  hosts: localhost 
  connection: local
  become: true

  pre_tasks:
    - name: Update repo's
      apt:
        update_cache: yes
      changed_when: False  
  tasks:
    - name: Zet de motd file.
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"

    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
