---
- name: Gebruik een template om de motd te vullen met informatie uit facts
  hosts: ALL 
  become: true

  tasks:
    - name: Zet de motd file.
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
